# Generated by Django 5.1.2 on 2025-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibraryaccount',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
