# Generated by Django 5.1.2 on 2025-02-13 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.IntegerField(choices=[(1, 'Deposit')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('loan_approval', models.BooleanField(default=False)),
                ('is_bank_bankrupt', models.BooleanField(blank=True, default=False, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.userlibraryaccount')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
